repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args:
          - --pattern=develop|main
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.2
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'  # pick a git hash / tag to point to
    hooks:
      -  id: flake8
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8
